import { notFound } from "next/navigation";

const sections = {
  requests: { title: "Requests / Telemetry", eyebrow: "Signal stream", description: "Real request telemetry will appear here after project integration. No sample traffic is generated by the shell." },
  routes: { title: "Routes", eyebrow: "Route performance", description: "Route performance belongs to F14 and remains intentionally unpopulated." },
  errors: { title: "Errors", eyebrow: "Incident surface", description: "Recent application errors belong to F15 and remain intentionally unpopulated." },
  settings: { title: "Settings", eyebrow: "Workspace controls", description: "Workspace settings will be added when their real backend contract is available." },
} as const;

export function generateStaticParams() {
  return Object.keys(sections).map((section) => ({ section }));
}

export default async function DashboardSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  const content = sections[section as keyof typeof sections];
  if (!content) notFound();
  return <div><p className="type-meta text-brand-steel">{content.eyebrow}</p><h1 className="type-page mt-3">{content.title}</h1><div className="mt-8 border-y border-border-subtle bg-surface-inset px-5 py-10 sm:px-8"><p className="font-mono text-[0.6875rem] tracking-[0.1em] text-text-muted uppercase">Reserved workspace</p><p className="mt-3 max-w-2xl text-sm leading-6 text-text-secondary">{content.description}</p></div></div>;
}
